log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://mail:mail@localhost:5493/mail?sslmode=disable"

amqp:
  topic: "mail"
  orchestrator: "orchestrator"
  unverified: "unverified-svc"
  publisher: "amqp://guest:guest@localhost:5672/" #module_publisher
  subscriber: "amqp://guest:guest@localhost:5672/" #module_receiver

listener:
  addr: :9010

jwt:
  secret: SuPeR SeCrEt PhRaSe
  refresh_life: 6h
  access_life: 10m5s

runners:
  registrar: 10m
  worker: 2h
  receiver: 30s
  sender: 30s

rate_limit:
  requests_amount: 1
  time_limit: 18s

registrator:
  outer_url: "http://localhost:8000/integrations/orchestrator/modules" #endpoint to register MODULE
  inner_url: "http://localhost:9010/integrations/mail" #endpoint to MODULE itself
  topic: "mail" #MODULE topic
  title: "Mail" #MODULE title
  prefix: ""
  is_module: true

# subject is the optional user to impersonate
mail:
  subject: maksym@acsgang.online

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: mail-module
  service_port: 80
